### ISSUE TITLE
March 26 Code Review and Feedback

### ISSUE THREAD

**Issue by LayneHaber** [rhlsthrm/moloch#4]
Full notes [here](https://docs.google.com/document/d/1D8DtqNSwqya4_UDfbMvl3eDST9mdWX8wVHc2D7EJnzM/edit).

1. Make createProposal payable, with a minimum deposit of 10 ETH (~5K).

2. Update createProposal to not use proposals.push(proposal), as it appends to the end of an array. Replace with an index counter.

3. Add a phase tag for each of the proposals, to indicate the current status (proposed, voting, done, gracePeriod). Ameen will write out the logic intended in a separate doc.

4. completeProposalVote must be able to be called on every proposal. Add logic so if the quorum hasn't been reached and voting period elapses, the vote is automatically assumed a failure and closed out. Close out votes periodically on client side cron job.

5. Note on dapp architecture: SQL db syncs up with chain after ~10blocks, and dapp makes calls to db rather than continuously using web3

**Comment by rhlsthrm** [comment]
Done in latest push.
